### ISSUE TITLE
Unable to connect to the Dashboard

### ISSUE THREAD

**Issue by armandsLa** [keenresearch/kaldi-ios-poc#10]
Unable to establish a connection to the Dashboard. Below is the code used to initialize the SDK, "appKey" has been replaced with <key> before posting in here.

Nothing is being sent to the Dashboard and logs doesn't seem to contain anything related to `KIOSUploader`. Default ATS configurations are being used.

```
        KIOSRecognizer.setLogLevel(.debug)
        KIOSRecognizer.initWithASRBundle("keenB2mQT-nnet3chain-en-us")
        // Shared instance of KIOSRecognizer
        KIOSRecognizer.sharedInstance()!.createJSONMetadata = true
        KIOSRecognizer.sharedInstance()!.createAudioRecordings = true
        // KIOSUploader
        if KIOSUploader.createDataUploadThread(for: recognizer, usingAppKey: "<key>") == false {
            print("Recognizer is unable to establish connection to Dashboard")
        }
```

**Comment by ognjentodic** [comment]
Currently, JSON metatada is created only when final result is computed, so if stopListening is called there will be no JSON file (and no upload to Dashboard). This may change in the future releases so that JSON file is created regardless of availability of final result. 

Generally, it's better to rely on VAD and let recognizer automatically time-out and compute final result.
