### ISSUE TITLE
Integrate with Swift

### ISSUE THREAD

**Issue by autumnssun** [keenresearch/kaldi-ios-poc#2]
I use swift.
As I dropped the framework file in my project.
and build I have this issue:

> Undefined symbols for architecture arm64:
>   "std::istream& std::istream::_M_extract<unsigned int>(unsigned int&)", referenced from:
>       void kaldi::ReadBasicType<unsigned int>(std::istream&, bool, unsigned int*) in KaldiIOS(build-tree-utils.o)
> 
> Is that an issue with the way I set up the project?
> the the framework was not build for arm64 architecture?
> Let know how to fix the problem

**Comment by ognjentodic** [comment]
We are not (yet) supporting swift, but here are couple of comments/suggestions:

I) The framework is built for arm64 and armv7 architectures. You can confirm that by running lipo against the static library:

`lipo -info KaldiIOS.framework/KaldiIOS`
`Architectures in the fat file: KaldiIOS.framework/KaldiIOS are: armv7 arm64`

If you don't get the output that matches the second line above (saying both armv7 and arm64 are part of the framework), make sure to [download](http://keenresearch.com/kaldi-ios-downloads/KaldiIOS-Framework.tar.gz) the latest version of the framework. In future releases we will add additional info in the framework directory structure so that version can be checked without running the app (right now, the framework will log the version, if log level is set to info)

II) Perhaps you can try to write a small Objective C test app to make sure everything is working properly and then work from that.

If none of this helps, would it be possible for you to share a sample swift app that demonstrates this problem (ideally, it would be trimmed down as much as possible). My guess is that, unless you are using some older version of the framework which somehow didn't include the arm64 slice (and I don't have any other reports on such issue), the problem is with the integration of the Objective C static library/framework in swift.

**Comment by pardeike** [comment]
It is rather easy to write some objective-c wrappers and then bridge them to swift. It's not that the framework has that many methods in the public API.

**Comment by ognjentodic** [comment]
We added documentation on the steps needed to integrate KeenASR SDK into Swift app:
http://keenresearch.com/keenasr-docs/docs/additional-docs/Swift-Support.html

You can also review a Swift PoC app: https://github.com/keenresearch/keenasr-swift-poc
