### ISSUE TITLE
Not getting final results when calling stopListeningAndReturnFinalResult

### ISSUE THREAD

**Issue by armandsLa** [keenresearch/kaldi-ios-poc#7]
Not getting anything from `recognizerFinalResult:forRecognizer:` when calling `stopListeningAndReturnFinalResult`. Recognizer state before calling stop is `KIOSRecognizerStateListening`.

Only thing that I changed was the VAD configurations as I needed recognizer to run for a longer period of time:
```
recognizer.setVADParameter(KIOSVadParameter.timeoutForNoSpeech, toValue: 60)
recognizer.setVADParameter(KIOSVadParameter.timeoutEndSilenceForAnyMatch, toValue: 60)
recognizer.setVADParameter(KIOSVadParameter.timeoutEndSilenceForGoodMatch, toValue: 60)
recognizer.setVADParameter(KIOSVadParameter.timeoutMaxDuration, toValue: 60)
```

**Comment by ognjentodic** [comment]
Oh, that's expected behavior... if you call stopListeningAndReturnFinalResult you will get the result as a return value of that method, not in the callback.

By the way, it's much better to use end-pointing (detecting end silence) to stop listening automatically than to call stopListeningAndReturnFinalResult.

**Comment by armandsLa** [comment]
Ah, you're right. I somehow missed the return type and presumed that the final results will be delivered via the delegate method. Thanks.
