### ISSUE TITLE
How to feed audio via Wi-Fi or BLE?

### ISSUE THREAD

**Issue by GordonHuangYong** [keenresearch/kaldi-ios-poc#8]
I can see that the audio data is from recording or auido path;
How to feed audio via Wi-Fi or BLE?

**Comment by ognjentodic** [comment]
For bluetooth, we automatically connect to the BT microphone if there is one. That's all that possible right now, since our SDK manages all the audio capture. 

If there is a viable use case for feeding raw audio (e.g. apple watch app, or audio coming from a different source), we could expose a method that you would use to feed the audio you captured. If that's of interest, please contact me at ogi@keenresearch.com

**Comment by GordonHuangYong** [comment]
Appliances with microphones connect to mobile via WiFi or Bluetooth Low Energy(not earphones), 
and  APP runs in background mode.
The audio comes from a appliance that user speak to, and then command sent by APP.

**Comment by ognjentodic** [comment]
It’s not possible right now, but it would not be that difficult to expose a method that would allow you to feed raw audio. 

Best to send me an email to ogi@keenresearch.com to discuss the details.
